export const DISH_LOADING = "ADD_DISH_LOADING";

// CREATE A NEW DISH
export const ADD_DISH = "ADD_DISH";
export const ADD_DISH_FAIL = "ADD_DISH_FAIL";
export const ADD_DISH_LOADING = "ADD_DISH_LOADING"

// GET ALL DISHES
export const GET_DISHES = "GET_DISHES";
export const GET_DISHES_FAIL = "GET_DISHES_FAIL";
export const GET_DISHES_LOADING = "GET_DISHES_LOADING";


// FOR CART
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_CART_ITEM = "INCREASE_CART_ITEM";
export const DECREASE_CART_ITEM = "DECREASE_CART_ITEM";
export const UPDATE_CART_NUMBER = "UPDATE_CART_NUMBER";
export const DELETE_FROM_CART = "DELETE_FROM_CART";

// FOR AUTH
export const SIGNUP = "SIGNUP"
export const SIGNUP_ERROR = "SIGNUP_ERROR"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_LOADING = "SIGNUP_LOADING"