export const DISH_LOADING = "ADD_DISH_LOADING";

// CREATE A NEW DISH
export const ADD_DISH = "ADD_DISH";
export const ADD_DISH_FAIL = "ADD_DISH_FAIL";
export const ADD_DISH_LOADING = "ADD_DISH_LOADING"

// GET ALL DISHES
export const GET_DISHES = "GET_DISHES";
export const GET_DISHES_FAIL = "GET_DISHES_FAIL";
export const GET_DISHES_LOADING = "GET_DISHES_LOADING";


// FOR CART
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_CART_ITEM = "INCREASE_CART_ITEM";
export const DECREASE_CART_ITEM = "DECREASE_CART_ITEM";
export const UPDATE_CART_NUMBER = "UPDATE_CART_NUMBER";
export const DELETE_FROM_CART = "DELETE_FROM_CART";

// FOR GOOGLE AUTH
export const SIGNUP_GOOGLE = "SIGNUP_GOOGLE"
export const SIGNUP_GOOGLE_ERROR = "SIGNUP_GOOGLE_ERROR"
export const SIGNUP_GOOGLE_SUCCESS = "SIGNUP_GOOGLE_SUCCESS"
export const SIGNUP_GOOGLE_LOADING = "SIGNUP_GOOGLE_LOADING"

// IS USER LOGGED IN?
export const LOG_OUT = "LOG_OUT"
export const IS_LOGGED_IN_SUCCESS = "IS_LOGGED_IN_SUCCESS"
export const IS_LOGGED_IN_ERROR = "IS_LOGGED_IN_ERROR"

// FOR LOCAL AUTH
export const SIGNUP_LOCAL = "SIGNUP_LOCAL"
export const SIGNUP_LOCAL_ERROR = "SIGNUP_LOCAL_ERROR"
export const SIGNUP_LOCAL_SUCCESS = "SIGNUP_LOCAL_SUCCESS"
export const SIGNUP_LOCAL_LOADING = "SIGNUP_LOCAL_LOADING"